export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';


export const FETCH_TIMESLOTS_TEACHER_START = 'FETCH_TIMESLOTS_TEACHER_START';
export const FETCH_TIMESLOTS_TEACHER_SUCCESS = 'FETCH_TIMESLOTS_TEACHER_SUCCESS';
export const FETCH_TIMESLOTS_TEACHER_FAIL = 'FETCH_TIMESLOTS_TEACHER_FAIL';

export const FETCH_TIMESLOTS_STUDENTS_START = 'FETCH_TIMESLOTS_STUDENTS_START';
export const FETCH_TIMESLOTS_STUDENTS_SUCCESS = 'FETCH_TIMESLOTS_STUDENTS_SUCCESS';
export const FETCH_TIMESLOTS_STUDENTS_FAIL = 'FETCH_TIMESLOTS_STUDENTS_FAIL';

export const FETCH_SUBJECTS_HOMEWORK_STUDENTS_START = 'FETCH_SUBJECTS_HOMEWORK_STUDENTS_START';
export const FETCH_SUBJECTS_HOMEWORK_STUDENTS_SUCCESS = 'FETCH_SUBJECTS_HOMEWORK_STUDENTS_SUCCESS';
export const FETCH_SUBJECTS_HOMEWORK_STUDENTS_FAIL = 'FETCH_SUBJECTS_HOMEWORK_STUDENTS_FAIL';

export const FETCH_HOMEWORK_ASSIGNED_ALLCLASSES_START = 'FETCH_HOMEWORK_ASSIGNED_ALLCLASSES_START';
export const FETCH_HOMEWORK_ASSIGNED_ALLCLASSES_SUCCESS = 'FETCH_HOMEWORK_ASSIGNED_ALLCLASSES_SUCCESS';
export const FETCH_HOMEWORK_ASSIGNED_ALLCLASSES_FAIL = 'FETCH_HOMEWORK_ASSIGNED_ALLCLASSES_FAIL';

export const CREATE_TIMETABLE_START = 'CREATE_TIMETABLE_START';
export const CREATE_TIMETABLE_SUCCESS = 'CREATE_TIMETABLE_SUCCESS';
export const CREATE_TIMETABLE_FAIL = 'CREATE_TIMETABLE_FAIL';

export const CREATE_HOMEWORK_START = 'CREATE_HOMEWORK_START';
export const CREATE_HOMEWORK_SUCCESS = 'CREATE_HOMEWORK_SUCCESS';
export const CREATE_HOMEWORK_FAIL = 'CREATE_HOMEWORK_FAIL';

export const CREATE_TEACHER_START = 'CREATE_TEACHER_START';
export const CREATE_TEACHER_SUCCESS = 'CREATE_TEACHER_SUCCESS';
export const CREATE_TEACHER_FAIL = 'CREATE_TEACHER_FAIL';

export const CREATE_STUDENT_START = 'CREATE_STUDENT_START';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';

export const CREATE_SECTION_START = 'CREATE_SECTION_START';
export const CREATE_SECTION_SUCCESS = 'CREATE_SECTION_SUCCESS';
export const CREATE_SECTION_FAIL = 'CREATE_SECTION_FAIL';

export const FETCH_TEACHERS_START = 'FETCH_TEACHERS_START';
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';
export const FETCH_TEACHERS_FAIL = 'FETCH_TEACHERS_FAIL';

export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';

export const FETCH_SECTIONS_START = 'FETCH_SECTIONS_START';
export const FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS';
export const FETCH_SECTIONS_FAIL = 'FETCH_SECTIONS_FAIL';

export const FETCH_ATTENDANCE_ALL_STUDENTS_START = 'FETCH_ATTENDANCE_OF_STUDENTS_START';
export const FETCH_ATTENDANCE_ALL_STUDENTS_SUCCESS = 'FETCH_ATTENDANCE_OF_STUDENTS_SUCCESS';
export const FETCH_ATTENDANCE_ALL_STUDENTS_FAIL = 'FETCH_ATTENDANCE_OF_STUDENTS_FAIL';

export const FETCH_ATTENDANCE_ACADEMICYEAR_STUDENT_START = 'FETCH_ATTENDANCE_ACADEMICYEAR_STUDENT_START';
export const FETCH_ATTENDANCE_ACADEMICYEAR_STUDENT_SUCCESS = 'FETCH_ATTENDANCE_ACADEMICYEAR_STUDENT_SUCCESS';
export const FETCH_ATTENDANCE_ACADEMICYEAR_STUDENT_FAIL = 'FETCH_ATTENDANCE_ACADEMICYEAR_STUDENT_FAIL';

export const FETCH_ATTENDANCE_MONTH_STUDENT_START = 'FETCH_ATTENDANCE_MONTH_STUDENT_START';
export const FETCH_ATTENDANCE_MONTH_STUDENT_SUCCESS = 'FETCH_ATTENDANCE_MONTH_STUDENT_SUCCESS';
export const FETCH_ATTENDANCE_MONTH_STUDENT_FAIL = 'FETCH_ATTENDANCE_MONTH_STUDENT_FAIL';

export const CREATE_ATTENDANCE_START = 'CREATE_ATTENDANCE_START';
export const CREATE_ATTENDANCE_SUCCESS = 'CREATE_ATTENDANCE_SUCCESS';
export const CREATE_ATTENDANCE_FAIL = 'CREATE_ATTENDANCE_FAIL';

export const CREATE_FEE_START = 'CREATE_FEE_START';
export const CREATE_FEE_SUCCESS = 'CREATE_FEE_SUCCESS';
export const CREATE_FEE_FAIL = 'CREATE_FEE_FAIL';

export const FETCH_FEE_START = 'FETCH_FEE_START';
export const FETCH_FEE_SUCCESS = 'FETCH_FEE_SUCCESS';
export const FETCH_FEE_FAIL = 'FETCH_FEE_FAIL';

export const CREATE_CLASS_FEE_START = 'CREATE_CLASS_FEE_START';
export const CREATE_CLASS_FEE_SUCCESS = 'CREATE_CLASS_FEE_SUCCESS';
export const CREATE_CLASS_FEE_FAIL = 'CREATE_CLASS_FEE_FAIL';

export const FETCH_CLASS_FEE_START = 'FETCH_CLASS_FEE_START';
export const FETCH_CLASS_FEE_SUCCESS = 'FETCH_CLASS_FEE_SUCCESS';
export const FETCH_CLASS_FEE_FAIL = 'FETCH_CLASS_FEE_FAIL';

export const CREATE_STUDENT_FEE_START = 'CREATE_STUDENT_FEE_START';
export const CREATE_STUDENT_FEE_SUCCESS = 'CREATE_STUDENT_FEE_SUCCESS';
export const CREATE_STUDENT_FEE_FAIL = 'CREATE_STUDENT_FEE_FAIL';

export const FETCH_STUDENT_FEE_START = 'FETCH_STUDENT_FEE_START';
export const FETCH_STUDENT_FEE_SUCCESS = 'FETCH_STUDENT_FEE_SUCCESS';
export const FETCH_STUDENT_FEE_FAIL = 'FETCH_STUDENT_FEE_FAIL';

export const UPDATE_STUDENT_FEE_START = 'UPDATE_STUDENT_FEE_START';
export const UPDATE_STUDENT_FEE_FAIL = 'UPDATE_STUDENT_FEE_FAIL';
export const UPDATE_STUDENT_FEE_SUCCESS = 'UPDATE_STUDENT_FEE_SUCCESS';